development:
  adapter: postgresql
  encoding: unicode
  database: doorman_dev
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: doorman_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: doorman_prod
  pool: 5
